import LOGO1 from "assets/sheet/logo1.png";
import LOGO2 from "assets/sheet/logo2.png";
import LOGO3 from "assets/sheet/logo3.png";
import LOGO4 from "assets/sheet/logo4.png";

export const MockSheetDetailPageData = {
  key: 1,
  date: "8/1",
  day: "SAT",
  count: 6,
  items: [
    {
      id: 123,
      logo: LOGO1,
      headerColor: "#b8c18c",
      name: "이진선",
      position: "ed",
      company: "ELLE",
      from: "EL손다예st",
      to: "VG최서영ed",
    },
    {
      id: 124,
      logo: LOGO2,
      headerColor: "#e1c668",
      name: "이진선",
      position: "ed",
      company: "ELLE",
      from: "EL손다예st",
      to: "VG최서영ed",
    },
    {
      id: 125,
      logo: LOGO3,
      headerColor: "#8cafc1",
      name: "이진선",
      position: "ed",
      company: "ELLE",
      from: "EL손다예st",
      to: "VG최서영ed",
    },
    {
      id: 126,
      logo: LOGO4,
      headerColor: "#d78979",
      name: "이진선",
      position: "ed",
      company: "ELLE",
      from: "EL손다예st",
      to: "VG최서영ed",
    },
    {
      id: 127,
      logo: LOGO1,
      headerColor: "#af8cc1",
      name: "이진선",
      position: "ed",
      company: "COSMOPOLITAN",
      from: "EL손다예st",
      to: "VG최서영ed",
    },
    {
      id: 128,
      logo: LOGO2,
      headerColor: "#e1af7b",
      name: "이진선",
      position: "ed",
      company: "Marie Claire",
      from: "EL손다예st",
      to: "VG최서영ed",
    },
  ],
};
export const MockSheetData = [
  {
    key: 1,
    date: "8/1",
    day: "SAT",
    count: 6,
    items: [
      {
        id: 123,
        logo: LOGO1,
        headerColor: "#b8c18c",
        name: "이진선",
        position: "ed",
        company: "ELLE",
        from: "EL손다예st",
        to: "VG최서영ed",
      },
      {
        id: 124,
        logo: LOGO2,
        headerColor: "#e1c668",
        name: "이진선",
        position: "ed",
        company: "ELLE",
        from: "EL손다예st",
        to: "VG최서영ed",
      },
      {
        id: 125,
        logo: LOGO3,
        headerColor: "#8cafc1",
        name: "이진선",
        position: "ed",
        company: "ELLE",
        from: "EL손다예st",
        to: "VG최서영ed",
      },
      {
        id: 126,
        logo: LOGO4,
        headerColor: "#d78979",
        name: "이진선",
        position: "ed",
        company: "ELLE",
        from: "EL손다예st",
        to: "VG최서영ed",
      },
      {
        id: 127,
        logo: LOGO1,
        headerColor: "#af8cc1",
        name: "이진선",
        position: "ed",
        company: "COSMOPOLITAN",
        from: "EL손다예st",
        to: "VG최서영ed",
      },
      {
        id: 128,
        logo: LOGO2,
        headerColor: "#e1af7b",
        name: "이진선",
        position: "ed",
        company: "Marie Claire",
        from: "EL손다예st",
        to: "VG최서영ed",
      },
    ],
  },
  {
    key: 2,
    date: "8/2",
    day: "SUN",
    count: 4,
    items: [
      {
        id: 123,
        logo: LOGO1,
        headerColor: "#b8c18c",
        name: "이진선",
        position: "ed",
        company: "ELLE",
        from: "EL손다예st",
        to: "VG최서영ed",
      },
      {
        id: 124,
        logo: LOGO2,
        headerColor: "#e1c668",
        name: "이진선",
        position: "ed",
        company: "ELLE",
        from: "EL손다예st",
        to: "VG최서영ed",
      },
      {
        id: 127,
        logo: LOGO1,
        headerColor: "#af8cc1",
        name: "이진선",
        position: "ed",
        company: "COSMOPOLITAN",
        from: "EL손다예st",
        to: "VG최서영ed",
      },
      {
        id: 128,
        logo: LOGO2,
        headerColor: "#e1af7b",
        name: "이진선",
        position: "ed",
        company: "Marie Claire",
        from: "EL손다예st",
        to: "VG최서영ed",
      },
    ],
  },
];
